from openalea.topvine.genotype import Genotype

Carignan = Genotype(NFI_mean=21.75,
                    NFI_sd=2.95,
                    SF_max_mean=266,
                    SF_max_sd=45.2,
                    IN_max_mean=8.14,
                    IN_max_sd=0.65,
                    slope_NFII_SFII=56.3397297297297,
                    slope_sd_NFII_SFII=5.95554253563631,
                    size_r_binorm=100,
                    mu_r_binorm=0.14,
                    name='Carignan',
                    rank_internode_at_max_length_mean=10.56,
                    rank_internode_at_max_length_sd=3.14,
                    fraction_apical_to_max_internode_length_mean=0.38,
                    fraction_apical_to_max_internode_length_sd=0.099,
                    rank_internode_at_max_leaf_area_mean=7.69,
                    rank_internode_at_max_leaf_area_sd=1.49,
                    fraction_initial_to_max_leaf_area_mean=0.306,
                    fraction_initial_to_max_leaf_area_sd=0.137,
                    )

Chasselas = Genotype(NFI_mean=23.56,
                     NFI_sd=4.13,
                     SF_max_mean=141,
                     SF_max_sd=39.2,
                     IN_max_mean=7.09,
                     IN_max_sd=0.46,
                     slope_NFII_SFII=37.3945206812653,
                     slope_sd_NFII_SFII=1.01518990961961,
                     size_r_binorm=6.83,
                     mu_r_binorm=1.59,
                     name='Chasselas',
                     rank_internode_at_max_length_mean=7.5,
                     rank_internode_at_max_length_sd=2.22,
                     fraction_apical_to_max_internode_length_mean=0.368,
                     fraction_apical_to_max_internode_length_sd=0.085,
                     rank_internode_at_max_leaf_area_mean=7,
                     rank_internode_at_max_leaf_area_sd=3.1,
                     fraction_initial_to_max_leaf_area_mean=0.278,
                     fraction_initial_to_max_leaf_area_sd=0.137,
                     )

Clairette = Genotype(NFI_mean=19.63,
                     NFI_sd=4.32,
                     SF_max_mean=236,
                     SF_max_sd=60.8,
                     IN_max_mean=9.92,
                     IN_max_sd=0.75,
                     slope_NFII_SFII=82.4779598662209,
                     slope_sd_NFII_SFII=3.42870130351829,
                     size_r_binorm=6.30,
                     mu_r_binorm=0.74,
                     name='Clairette',
                     rank_internode_at_max_length_mean=10.19,
                     rank_internode_at_max_length_sd=2.81,
                     fraction_apical_to_max_internode_length_mean=0.317,
                     fraction_apical_to_max_internode_length_sd=0.106,
                     rank_internode_at_max_leaf_area_mean=7.31,
                     rank_internode_at_max_leaf_area_sd=1.99,
                     fraction_initial_to_max_leaf_area_mean=0.217,
                     fraction_initial_to_max_leaf_area_sd=0.098,
                     )

Marselan = Genotype(NFI_mean=24.63,
                    NFI_sd=2.45,
                    SF_max_mean=155,
                    SF_max_sd=26.7,
                    IN_max_mean=7.41,
                    IN_max_sd=0.34,
                    slope_NFII_SFII=45.2619648885888,
                    slope_sd_NFII_SFII=0.820875830879395,
                    size_r_binorm=2.96,
                    mu_r_binorm=1.63,
                    name='Marselan',
                    rank_internode_at_max_length_mean=8.25,
                    rank_internode_at_max_length_sd=2.35,
                    fraction_apical_to_max_internode_length_mean=0.364,
                    fraction_apical_to_max_internode_length_sd=0.092,
                    rank_internode_at_max_leaf_area_mean=8.06,
                    rank_internode_at_max_leaf_area_sd=0.85,
                    fraction_initial_to_max_leaf_area_mean=0.203,
                    fraction_initial_to_max_leaf_area_sd=0.104,
                    )

Mauzac = Genotype(NFI_mean=28.8,
                  NFI_sd=2.96,
                  SF_max_mean=149,
                  SF_max_sd=31,
                  IN_max_mean=8.3,
                  IN_max_sd=0.4,
                  slope_NFII_SFII=36.7865159010601,
                  slope_sd_NFII_SFII=0.924857615180504,
                  size_r_binorm=4.83,
                  mu_r_binorm=2.03,
                  name='Mauzac',
                  rank_internode_at_max_length_mean=9.06,
                  rank_internode_at_max_length_sd=2.24,
                  fraction_apical_to_max_internode_length_mean=0.316,
                  fraction_apical_to_max_internode_length_sd=0.12,
                  rank_internode_at_max_leaf_area_mean=8.13,
                  rank_internode_at_max_leaf_area_sd=1.93,
                  fraction_initial_to_max_leaf_area_mean=0.255,
                  fraction_initial_to_max_leaf_area_sd=0.111,
                  )

Mourverde = Genotype(NFI_mean=16.94,
                     NFI_sd=1.90,
                     SF_max_mean=136,
                     SF_max_sd=27.4,
                     IN_max_mean=6.43,
                     IN_max_sd=0.62,
                     slope_NFII_SFII=44.0457740585775,
                     slope_sd_NFII_SFII=2.1481855251514,
                     size_r_binorm=4.21,
                     mu_r_binorm=0.73,
                     name='Mourverde',
                     rank_internode_at_max_length_mean=7.81,
                     rank_internode_at_max_length_sd=2.93,
                     fraction_apical_to_max_internode_length_mean=0.436,
                     fraction_apical_to_max_internode_length_sd=0.136,
                     rank_internode_at_max_leaf_area_mean=8.5,
                     rank_internode_at_max_leaf_area_sd=2.66,
                     fraction_initial_to_max_leaf_area_mean=0.168,
                     fraction_initial_to_max_leaf_area_sd=0.092,
                     )

Petit_Verdot = Genotype(NFI_mean=20.50,
                        NFI_sd=3.05,
                        SF_max_mean=117,
                        SF_max_sd=15.7,
                        IN_max_mean=5.53,
                        IN_max_sd=0.65,
                        slope_NFII_SFII=27.8233043478261,
                        slope_sd_NFII_SFII=1.73231611270049,
                        size_r_binorm=3.20,
                        mu_r_binorm=0.66,
                        name='Petit_Verdot',
                        rank_internode_at_max_length_mean=9.75,
                        rank_internode_at_max_length_sd=3.64,
                        fraction_apical_to_max_internode_length_mean=0.429,
                        fraction_apical_to_max_internode_length_sd=0.141,
                        rank_internode_at_max_leaf_area_mean=8.38,
                        rank_internode_at_max_leaf_area_sd=2.36,
                        fraction_initial_to_max_leaf_area_mean=0.166,
                        fraction_initial_to_max_leaf_area_sd=0.096,
                        )

Vermentino = Genotype(NFI_mean=24.38,
                      NFI_sd=2.33,
                      SF_max_mean=279,
                      SF_max_sd=58.5,
                      IN_max_mean=11.71,
                      IN_max_sd=0.91,
                      slope_NFII_SFII=87.6333706965573,
                      slope_sd_NFII_SFII=2.57485509011939,
                      size_r_binorm=1.68,
                      mu_r_binorm=1.27,
                      name='Vermentino',
                      rank_internode_at_max_length_mean=11.5,
                      rank_internode_at_max_length_sd=3.35,
                      fraction_apical_to_max_internode_length_mean=0.399,
                      fraction_apical_to_max_internode_length_sd=0.127,
                      rank_internode_at_max_leaf_area_mean=8.81,
                      rank_internode_at_max_leaf_area_sd=2.83,
                      fraction_initial_to_max_leaf_area_mean=0.199,
                      fraction_initial_to_max_leaf_area_sd=0.097,
                      )
