{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}
{% set project = pyproject["project"] %}
{% set version = environ.get("GIT_DESCRIBE_TAG", "0.0.0") %}
{% set build_deps = pyproject.get("build-system", {}).get("requires", []) %}
{% set deps = pyproject.get("project", {}).get("dependencies", []) %}
{% set conda_deps = pyproject.get("tool", {}).get("conda", {}).get("environment", {}).get("dependencies", []) %}
{% set test_deps = pyproject.get("project", {}).get("optional-dependencies", {}).get("test", []) %}

package:
  name: openalea.topvine
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    {% for dep in build_deps %}
    - {{ dep }}
    {% endfor %}

  run:
    - python
    {% for dep in deps + conda_deps %}
    - {{ dep }}
    {% endfor %}

test:
  requires:
    - pytest
    {% for dep in test_deps %}
    - {{ dep }}
    {% endfor %}
  imports:
    - openalea.topvine
  source_files:
    - test/**
  commands:
    - python -m unittest discover -s test -p "*.py"

about:
  home: {{ project.get("urls", {}).get("Homepage", "") }}
  license: {{ project.get("license", "") }}
  summary: {{ project.get("description", "") }}