from alinea.topvine.generate_rameau_moyen import Genotype

Carignan = Genotype(NFI_mean=21.75,
                    NFI_sd=2.95,
                    SF_max_mean=266,
                    SF_max_sd=45.2,
                    max_normalized_rank_SF=0.35,
                    intercept_0_SF=0,
                    intercept_1_SF=0.44,
                    IN_max_mean=8.14,
                    IN_max_sd=0.65,
                    max_normalized_rank_IN=0.34,
                    intercept_0_IN=0.31,
                    intercept_1_IN=0.126,
                    slope_NFII_SFII=153.90,
                    intercept_NFII_SFII=-103.2,
                    size_r_binorm=100,
                    mu_r_binorm=0.14
                    )

Chasselas = Genotype(NFI_mean=23.56,
                     NFI_sd=4.13,
                     SF_max_mean=141,
                     SF_max_sd=39.2,
                     max_normalized_rank_SF=0.25,
                     intercept_0_SF=0,
                     intercept_1_SF=0.43,
                     IN_max_mean=7.09,
                     IN_max_sd=0.46,
                     max_normalized_rank_IN=0.26,
                     intercept_0_IN=0.22,
                     intercept_1_IN=0.179,
                     slope_NFII_SFII=50.05,
                     intercept_NFII_SFII=-35.56,
                     size_r_binorm=6.83,
                     mu_r_binorm=1.59
                     )

Clairette = Genotype(NFI_mean=19.63,
                     NFI_sd=4.32,
                     SF_max_mean=236,
                     SF_max_sd=60.8,
                     max_normalized_rank_SF=0.38,
                     intercept_0_SF=0,
                     intercept_1_SF=0.48,
                     IN_max_mean=9.92,
                     IN_max_sd=0.75,
                     max_normalized_rank_IN=0.34,
                     intercept_0_IN=0.25,
                     intercept_1_IN=0.202,
                     slope_NFII_SFII=109.45,
                     intercept_NFII_SFII=-60.15,
                     size_r_binorm=6.30,
                     mu_r_binorm=0.74
                     )

Marselan = Genotype(NFI_mean=24.63,
                    NFI_sd=2.45,
                    SF_max_mean=155,
                    SF_max_sd=26.7,
                    max_normalized_rank_SF=0.26,
                    intercept_0_SF=0,
                    intercept_1_SF=0.35,
                    IN_max_mean=7.41,
                    IN_max_sd=0.34,
                    max_normalized_rank_IN=0.28,
                    intercept_0_IN=0.14,
                    intercept_1_IN=0.291,
                    slope_NFII_SFII=56.92,
                    intercept_NFII_SFII=-36.66,
                    size_r_binorm=2.96,
                    mu_r_binorm=1.63
                    )

Mauzac = Genotype(NFI_mean=28.8,
                  NFI_sd=2.96,
                  SF_max_mean=149,
                  SF_max_sd=31.8,
                  max_normalized_rank_SF=0.29,
                  intercept_0_SF=0,
                  intercept_1_SF=0.41,
                  IN_max_mean=8.3,
                  IN_max_sd=0.4,
                  max_normalized_rank_IN=0.27,
                  intercept_0_IN=0.22,
                  intercept_1_IN=0.21,
                  slope_NFII_SFII=51.67,
                  intercept_NFII_SFII=-44.91,
                  size_r_binorm=4.83,
                  mu_r_binorm=2.03
                  )

Mourverde = Genotype(NFI_mean=16.94,
                     NFI_sd=1.90,
                     SF_max_mean=136,
                     SF_max_sd=27.4,
                     max_normalized_rank_SF=0.38,
                     intercept_0_SF=0,
                     intercept_1_SF=0.53,
                     IN_max_mean=6.43,
                     IN_max_sd=0.62,
                     max_normalized_rank_IN=0.39,
                     intercept_0_IN=0.16,
                     intercept_1_IN=0.247,
                     slope_NFII_SFII=54.96,
                     intercept_NFII_SFII=-21.92,
                     size_r_binorm=4.21,
                     mu_r_binorm=0.73
                     )

Petit_Verdot = Genotype(NFI_mean=20.50,
                        NFI_sd=3.05,
                        SF_max_mean=117,
                        SF_max_sd=15.7,
                        max_normalized_rank_SF=0.32,
                        intercept_0_SF=0.1,
                        intercept_1_SF=0.48,
                        IN_max_mean=5.53,
                        IN_max_sd=0.65,
                        max_normalized_rank_IN=0.33,
                        intercept_0_IN=0.23,
                        intercept_1_IN=0.213,
                        slope_NFII_SFII=42.09,
                        intercept_NFII_SFII=-27.52,
                        size_r_binorm=3.20,
                        mu_r_binorm=0.66
                        )

Vermentino = Genotype(NFI_mean=24.38,
                      NFI_sd=2.33,
                      SF_max_mean=279,
                      SF_max_sd=58.5,
                      max_normalized_rank_SF=0.46,
                      intercept_0_SF=0.1,
                      intercept_1_SF=0.46,
                      IN_max_mean=11.71,
                      IN_max_sd=0.91,
                      max_normalized_rank_IN=0.34,
                      intercept_0_IN=0.26,
                      intercept_1_IN=0.207,
                      slope_NFII_SFII=98.25,
                      intercept_NFII_SFII=-69.42,
                      size_r_binorm=1.68,
                      mu_r_binorm=1.27
                      )